"""initial schema

Revision ID: 0dd1def51211
Revises: 
Create Date: 2026-06-29 21:14:50.826620

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0dd1def51211'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cases',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('case_ref', sa.String(), nullable=False),
    sa.Column('status', sa.Enum('active', 'archived', name='case_status'), server_default='active', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('clinicians',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('role', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('assessments',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('case_id', sa.UUID(), nullable=False),
    sa.Column('assessment_date', sa.Date(), nullable=False),
    sa.Column('is_baseline', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('length_cm', sa.Float(), nullable=False),
    sa.Column('width_cm', sa.Float(), nullable=False),
    sa.Column('depth_cm', sa.Float(), nullable=False),
    sa.Column('area_cm2', sa.Float(), nullable=False),
    sa.Column('volume_cm3', sa.Float(), nullable=False),
    sa.Column('tissue_type', sa.String(), nullable=False),
    sa.Column('drainage_amount', sa.String(), nullable=False),
    sa.Column('drainage_type', sa.String(), nullable=False),
    sa.Column('periwound', sa.String(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('review_status', sa.Enum('pending', 'accepted', 'overridden', name='review_status'), server_default='pending', nullable=False),
    sa.Column('clinician_classification', sa.Enum('improving', 'stable', 'deteriorating', name='healing_classification'), nullable=True),
    sa.Column('override_reason', sa.Text(), nullable=True),
    sa.Column('note_draft', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_assessments_case_id'), 'assessments', ['case_id'], unique=False)
    op.create_table('ai_findings',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('assessment_id', sa.UUID(), nullable=False),
    sa.Column('model_version', sa.String(), nullable=False),
    sa.Column('vision_output', sa.Text(), nullable=True),
    sa.Column('area_delta_pct', sa.Float(), nullable=True),
    sa.Column('tissue_change', sa.String(), nullable=True),
    sa.Column('drainage_change', sa.String(), nullable=True),
    sa.Column('ai_available', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('failure_reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['assessment_id'], ['assessments.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ai_findings_assessment_id'), 'ai_findings', ['assessment_id'], unique=True)
    op.create_table('audit_logs',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('assessment_id', sa.UUID(), nullable=False),
    sa.Column('service_name', sa.String(), nullable=False),
    sa.Column('prompt_sent', sa.Text(), nullable=True),
    sa.Column('response_received', sa.Text(), nullable=True),
    sa.Column('model_version', sa.String(), nullable=True),
    sa.Column('latency_ms', sa.Integer(), nullable=True),
    sa.Column('success', sa.Boolean(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['assessment_id'], ['assessments.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_logs_assessment_id'), 'audit_logs', ['assessment_id'], unique=False)
    op.create_table('images',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('assessment_id', sa.UUID(), nullable=False),
    sa.Column('storage_url', sa.String(), nullable=False),
    sa.Column('filename', sa.String(), nullable=False),
    sa.Column('mime_type', sa.String(), nullable=False),
    sa.Column('file_size_bytes', sa.Integer(), nullable=False),
    sa.Column('uploaded_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['assessment_id'], ['assessments.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_images_assessment_id'), 'images', ['assessment_id'], unique=False)
    op.create_table('validation_reviews',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('assessment_id', sa.UUID(), nullable=False),
    sa.Column('reviewer_id', sa.UUID(), nullable=True),
    sa.Column('ai_classification', sa.Enum('improving', 'stable', 'deteriorating', name='healing_classification'), nullable=True),
    sa.Column('ai_confidence', sa.Float(), nullable=True),
    sa.Column('clinician_classification', sa.Enum('improving', 'stable', 'deteriorating', name='healing_classification'), nullable=False),
    sa.Column('match', sa.Boolean(), nullable=True),
    sa.Column('ai_available', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('fitzpatrick_scale', sa.Enum('I', 'II', 'III', 'IV', 'V', 'VI', name='fitzpatrick_scale'), nullable=True),
    sa.Column('reviewer_verdict', sa.Enum('correct', 'partial', 'incorrect', name='reviewer_verdict'), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['assessment_id'], ['assessments.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['reviewer_id'], ['clinicians.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_validation_reviews_assessment_id'), 'validation_reviews', ['assessment_id'], unique=True)
    op.create_index(op.f('ix_validation_reviews_reviewer_id'), 'validation_reviews', ['reviewer_id'], unique=False)
    op.create_table('ai_classifications',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('ai_finding_id', sa.UUID(), nullable=False),
    sa.Column('classification', sa.Enum('improving', 'stable', 'deteriorating', name='healing_classification'), nullable=False),
    sa.Column('confidence_score', sa.Float(), nullable=False),
    sa.Column('area_signal_score', sa.Float(), nullable=False),
    sa.Column('tissue_signal_score', sa.Float(), nullable=False),
    sa.Column('drainage_signal_score', sa.Float(), nullable=False),
    sa.Column('evidence_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['ai_finding_id'], ['ai_findings.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ai_classifications_ai_finding_id'), 'ai_classifications', ['ai_finding_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ai_classifications_ai_finding_id'), table_name='ai_classifications')
    op.drop_table('ai_classifications')
    op.drop_index(op.f('ix_validation_reviews_reviewer_id'), table_name='validation_reviews')
    op.drop_index(op.f('ix_validation_reviews_assessment_id'), table_name='validation_reviews')
    op.drop_table('validation_reviews')
    op.drop_index(op.f('ix_images_assessment_id'), table_name='images')
    op.drop_table('images')
    op.drop_index(op.f('ix_audit_logs_assessment_id'), table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index(op.f('ix_ai_findings_assessment_id'), table_name='ai_findings')
    op.drop_table('ai_findings')
    op.drop_index(op.f('ix_assessments_case_id'), table_name='assessments')
    op.drop_table('assessments')
    op.drop_table('clinicians')
    op.drop_table('cases')
    # ### end Alembic commands ###
    # Postgres ENUM types are not dropped automatically when their owning
    # tables are dropped — clean them up explicitly so downgrade/upgrade
    # cycles are repeatable.
    op.execute("DROP TYPE IF EXISTS fitzpatrick_scale")
    op.execute("DROP TYPE IF EXISTS reviewer_verdict")
    op.execute("DROP TYPE IF EXISTS healing_classification")
    op.execute("DROP TYPE IF EXISTS review_status")
    op.execute("DROP TYPE IF EXISTS case_status")
